{% set version = "2.2-6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rpmg
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RPMG_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RPMG/RPMG_{{ version }}.tar.gz
  sha256: 1650e3a90b6c3b8e0023b11791bfb446d39d6e10408a1e0216951d36754ac319

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('RPMG')"           # [not win]
    - "\"%R%\" -e \"library('RPMG')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=RPMG
  license: GPL-2.0-or-later
  summary: Really Poor Man's Graphical User Interface, used to create interactive R analysis sessions with simple R commands.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: RPMG
# Type: Package
# Title: Graphical User Interface (GUI) for Interactive R Analysis Sessions
# Version: 2.2-3
# Date: 2019-09-20
# Authors@R: c(person(given="Jonathan M.", family="Lees", role = c("aut", "cre"),email = "jonathan.lees@unc.edu"), person("Jake", "Anderson", role = "ctb", email = "ajakef@gmail.com"))
# Author: Jonathan M. Lees [aut, cre], Jake Anderson [ctb]
# Maintainer: Jonathan M. Lees <jonathan.lees@unc.edu>
# Description: Really Poor Man's Graphical User Interface, used to create interactive R analysis sessions with simple R commands.
# License: GPL (>= 2)
# Packaged: 2019-09-20 14:34:59 UTC; lees
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2019-09-23 10:30:02 UTC
