appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: ItmkhaURgzpV2m+Y02nC7HNcl7jSNP6e9QcLT5PW0L2DLt0Y+tvuAAsa8thGPEtIo/DCvbmgpSlpK61weY8Xv+Pg2dX4SFeKqyJ7jePqPpAG37pAGiWqeo1BcNVUSOZB3PiNY/QWfyh2IpSn4/HQY7KtY3H7lRSBwLjvP6F/ts4mSloM4ZeqkR789lHXyJWRw9RKWc+TWGDKhkQ9KH9onkNy+3ehr1++9EBP25ghPmJanuXeIeF6fp79qjm7vG4jNvZFGFBcWpz8w+oycgXTIQtbHHiROkExqzJCYu0vvOeQv441EEDD093WtO/4/48ztaoN+tU5GK5/ZtjJaB9f+4VP+wwLJxLR2SPSdKE36v3ZOwrvTbgyG8XEpWx0uW2QvR5ygR0pU6WzxEeOPcHi09zrSvePzr7K7+UZ8GJLPTlVKb7aVj2S/cglgNOtyP87BpNeJEvlR0MOaoSDw8MEMcEsyBomm1yW7QtVd1OqSQA+Dff0931ESD5eKJVPUpcW9V/Ish/dvspgi71wEeWWEtflzU85Sw+qsQVe46vI114+dLS6f8ya/hf0vWB5ENaRP0aH2TomOu3/jK+wt5ZVeXf35YRB4wrJlKOikenkFmLESlzFfEfmmiJzKylMhCbrU48f53g3sjcvLYi8U9FOOsB76Tj44XPKWB3Pc6S848E=
conda_forge_output_validation: false
